### PR TITLE
Multiple additions

### PR DESCRIPTION
**Pull request by turtledude01**
- Added option to disable mobs entering a "mob=false" region
- Added option to make upkeep per block instead of per player
- Allow extra characters like ._-" in Nation and Zone name
- Added option to show Nation owners Title in chat prefix

### CODE REVIEW

**Comment by turtledude01** [comment]
I found a few small issues with the changes in this that i am fixing right now, such as
- No numbers allowed in nation/zone names
- Other small things

**Comment by turtledude01** [comment]
OOf, so I didnt realize it was automatically adding all new push's to this pull request, anyways, I have thoroughly tested everything that is in my forks master branch, from what i have seen, everything works perfectly.  There is one thing that I'm just not sure on.  The current state of the /n unclaim command and its refund is that, in my fork, if the Server account cant afford it, the player will still be refunded the money that they would normally get.  Thoughts on this and the OK to continue doing things like this would be amazing, I have really enjoyed tinkering with this plugins code to make it A) more interesting and B) more similar to towny.  
Also, if you would rather me delete this pull request and reset my repo to where there is only 1 commit in it I am more than willing to do that since a few of the commits here are due to me prematurely committing something I had not tested.

**Comment by yepidoodles** [comment]
Would you be able to make me a .jar of this for me?

**Comment by turtledude01** [comment]
@yepidoodles Sure, I can do that in a few minutes, I'm first fixing a major issue in the plugin (some rects are wrapping into negaitves)

**Comment by turtledude01** [comment]
@yepidoodles I have no guarantees that this build is 100% working as I literally JUST modified a few things attempting to fix bugs, but here it is: https://downloads.turtle-mc.org/nations-turtledude01.jar
Current builds of this branch will be uploaded and available at that link from now on

Also, if you plan on using this version on top of the original version of nations, be sure to add the required option to every nations file in config/nations/nations/<uuid>.json you need to add '  "tag": "", ' just below the 'admin: false, ' line

**Comment by yepidoodles** [comment]
Would you be able to give me an example of the nations file with the addition?

**Comment by turtledude01** [comment]
As I see the dev is active again I'll just close this and readd what I have to at a later point

**Pull request closed without merging**
