### PR TITLE
Updated German translation file

### PR DESCRIPTION
**Pull request by randombyte-developer**
- Fixed the existing German translation
- Added missing strings from English to German
- Sorted German alphabetically
- Sorted English alphabetically
- ~~Added myself to the authors list~~

Ready to be merged

### CODE REVIEW

**Comment by TheoKah** [comment]
Thank your for updating the language files. I'll merge this part when I'm on my computer.

About adding yourself to the author list within the plugin itself, it is a bit overkill. We try to put on this list only people that brings a significant amount of code to the project. (I only added myself to the list a couple days ago, for technical reasons)

**Comment by randombyte-developer** [comment]
Ok

**Comment by randombyte-developer** [comment]
Ready to be merged @TheoKah

**Comment by TheoKah** [comment]
Thanks :)

**Pull request merged**
