### PR TITLE
Fixed grammar error.

### PR DESCRIPTION
**Pull request by yepidoodles**

### CODE REVIEW

**Comment by TheoKah** [comment]
Can you fix it in the code too?

**Comment by yepidoodles** [comment]
Not sure why that's conflicting

**Comment by TheoKah** [comment]
Conflicting because you are not using the last version: pull again

Also, you will need to change usage in the code too

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version `v3.0`](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all prior pull requests. Nonetheless, thank you for your contribution.

**Pull request closed without merging**
